### ISSUE TITLE
Make available on NPM

### ISSUE THREAD

**Issue by selbekk** [ajgarn/CanvasImageUploader#1]
Hi!

Great project, loving it. Could you please make it available on NPM? 

Simply run `npm init`, add a dependency on `exif-js` and fill out the rest of the fields as you feel like. Then you run `npm publish`, and good stuff happens.

**Comment by ajgarn** [comment]
Thanks!

I just published it to https://www.npmjs.com/package/canvas-image-uploader. Let me know if there are any problems.
